/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "burano": {
    "base": "burano",
    "width": 800,
    "height": 533,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 1280,
    "height": 852,
    "fallbackWidth": 1280,
    "fallbackHeight": 852,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coastal": {
    "base": "coastal",
    "width": 1280,
    "height": 852,
    "fallbackWidth": 1280,
    "fallbackHeight": 852,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 1280,
    "height": 853,
    "fallbackWidth": 1280,
    "fallbackHeight": 853,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1280,
    "height": 1920,
    "fallbackWidth": 1280,
    "fallbackHeight": 1920,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 800,
    "height": 533,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 800,
    "height": 1200,
    "fallbackWidth": 800,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food-and-wine": {
    "base": "food-and-wine",
    "width": 800,
    "height": 1200,
    "fallbackWidth": 800,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "gondola": {
    "base": "gondola",
    "width": 778,
    "height": 518,
    "fallbackWidth": 778,
    "fallbackHeight": 518,
    "widths": [
      320,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "grand-canal": {
    "base": "grand-canal",
    "width": 800,
    "height": 538,
    "fallbackWidth": 800,
    "fallbackHeight": 538,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero": {
    "base": "hero",
    "width": 1280,
    "height": 568,
    "fallbackWidth": 1280,
    "fallbackHeight": 568,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1280,
    "height": 568,
    "fallbackWidth": 1280,
    "fallbackHeight": 568,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 800,
    "height": 356,
    "fallbackWidth": 800,
    "fallbackHeight": 356,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "murano": {
    "base": "murano",
    "width": 800,
    "height": 600,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "nature": {
    "base": "nature",
    "width": 1280,
    "height": 852,
    "fallbackWidth": 1280,
    "fallbackHeight": 852,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1280,
    "height": 853,
    "fallbackWidth": 1280,
    "fallbackHeight": 853,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "photography": {
    "base": "photography",
    "width": 1280,
    "height": 860,
    "fallbackWidth": 1280,
    "fallbackHeight": 860,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 778,
    "height": 518,
    "fallbackWidth": 778,
    "fallbackHeight": 518,
    "widths": [
      320,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "rialto": {
    "base": "rialto",
    "width": 800,
    "height": 355,
    "fallbackWidth": 800,
    "fallbackHeight": 355,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "st-marks": {
    "base": "st-marks",
    "width": 800,
    "height": 1061,
    "fallbackWidth": 800,
    "fallbackHeight": 1061,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "viewpoints": {
    "base": "viewpoints",
    "width": 800,
    "height": 538,
    "fallbackWidth": 800,
    "fallbackHeight": 538,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 800,
    "height": 1200,
    "fallbackWidth": 800,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 800,
    "height": 1200,
    "fallbackWidth": 800,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
